repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        description: wemake-python-styleguide enforcement
        args: ['--config=setup.cfg']
        language: python
        types: [python]
